let TIMPO_DE_ESPERA = 1500
let VELOCIDAD = 50
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, VELOCIDAD)
basic.pause(TIMPO_DE_ESPERA)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, VELOCIDAD)
